on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
run-name: release-please => ${{  github.event.head_commit.message }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    env:
      RELEASE_PLEASE_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
    steps:
      - uses: googleapis/release-please-action@v4
        if: ${{ env.RELEASE_PLEASE_TOKEN != '' }}
        with:
          token: ${{ env.RELEASE_PLEASE_TOKEN }}
          release-type: node
