name: Release
run-name: Release => ${{  github.event.head_commit.message }}

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    secrets:
      token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
